steps:
- task: GoTool@0
  inputs:
    version: '1.16.x'
    goPath: '/home/vsts/work/1/s/go'
    goBin: '/home/vsts/work/1/s/go/bin'
- bash: |
    cd $(Pipeline.Workspace)/s
    git clone --branch $(WORKBRANCH) https://$(PIPELINE_USER):$(PIPELINE_TOKEN)@$(SPEC_REPO_URL)
    git clone --branch $(WORKBRANCH) https://$(PIPELINE_USER):$(PIPELINE_TOKEN)@$(SDK_REPO_URL)
    echo "https://$(PIPELINE_USER):$(PIPELINE_TOKEN)@github.com" > ~/.git-credentials
    cd azure-sdk-for-go
    git config credential.helper store ; git config --global user.email "chunyu@microsoft.com";git config --global user.name "chunyu3"
  displayName: 'pull repo'
- bash: |
    rpAndPackages=($(rpAndPackages))
    for (( i=1; i<${#rpAndPackages[@]}; i++ ));
    do
      cd $(Pipeline.Workspace)/s/azure-sdk-for-go/sdk/${rpAndPackages[0]}/${rpAndPackages[$i]}
      go mod tidy
      go build 1>>$(Pipeline.Workspace)/s/$(TASK_KEY).log 2>&1
      
      if [ "$?" != "0" ]; then
        echo -e "\e[31m[$(date -u)] ERROR: [$(ResourceProvider)]: Compile Generated code failed"
        echo "##vso[task.setvariable variable=Task_Result]failure"
        exit 1
      fi
    done
  displayName: 'build go-sdk'